name: MaSuitePunish
version: ${project.version}
main: fi.matiaspaavilainen.masuitepunish.bukkit.MaSuitePunish
api-version: 1.13
authors: [Masa]
depend: [MaSuiteCore]
description: Punishment system
commands:
  ban:
    description: BanCommand specific player
    aliases: [tempban, banplayer]
    permission: masuitepunish.ban
  mute:
    description: MuteCommand specific player
    aliases: [tempmute, muteplayer]
    permission: masuitepunish.mute
  kick:
    description: KickCommand specific player
    aliases: [kickplayer]
    permission: masuitepunish.kick
  kickall:
    description: KickCommand all players
    aliases: [kickallplayers]
    permission: masuitepunish.kick.all
  warn:
    description: WarnCommand specific player
    aliases: [warnplayer]
    permission: masuitepunish.warn
  report:
    description: ReportCommand specific player
    aliases: [reportplayer]
    permission: masuitepunish.report
