name: MaSuitePunish
version: ${project.version}
main: fi.matiaspaavilainen.masuitepunish.bukkit.MaSuitePunish
api-version: 1.13
authors: [Masa]
depend: [MaSuiteCore]
description: Punishment system
commands:
  ban:
    description: Ban specific player
    aliases: [tempban, banplayer]
    permission: masuitepunish.ban
  mute:
    description: Mute specific player
    aliases: [tempmute, muteplayer]
    permission: masuitepunish.mute
  kick:
    description: Kick specific player
    aliases: [kickplayer]
    permission: masuitepunish.kick
  kickall:
    description: Kick all players
    aliases: [kickallplayers]
    permission: masuitepunish.kick.all
  warn:
    description: Warn specific player
    aliases: [warnplayer]
    permission: masuitepunish.warn
  report:
    description: Report specific player
    aliases: [reportplayer]
    permission: masuitepunish.report
